name: Apps build

on:
  repository_dispatch:
    types: [build-custom-app] # 自定义一个事件名称

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frappe_docker
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/layered/Containerfile
          push: true
          # 使用 build-args 传递你指定的参数
          build-args: |
            FRAPPE_PATH=https://github.com/adam7seven/frappe
            FRAPPE_BRANCH=main
            APPS_JSON_BASE64=${{ github.event.client_payload.apps_json_base64 }}# 接收来自 client_payload 的 Base64 字符串
          # 镜像标签
          tags: adam7/${{github.event.client_payload.app_name}}:develop
          # 利用缓存加速后续构建
          cache-from: type=gha
          cache-to: type=gha,mode=max
